CREATE TABLE `accounts` (
	`id` varchar(36) NOT NULL,
	`transaction_type` varchar(50) NOT NULL,
	`reference_id` varchar(36),
	`reference_number` varchar(50),
	`revenue` decimal(10,2) NOT NULL DEFAULT '0.00',
	`cost` decimal(10,2) NOT NULL DEFAULT '0.00',
	`profit` decimal(10,2) NOT NULL DEFAULT '0.00',
	`tax_amount` decimal(10,2) DEFAULT '0.00',
	`discount_amount` decimal(10,2) DEFAULT '0.00',
	`shipping_cost` decimal(10,2) DEFAULT '0.00',
	`product_id` varchar(36),
	`product_name` varchar(255),
	`category` varchar(100),
	`quantity` int DEFAULT 0,
	`customer_name` varchar(100),
	`customer_email` varchar(150),
	`notes` text,
	`fiscal_year` int,
	`fiscal_month` int,
	`fiscal_quarter` int,
	`transaction_date` timestamp DEFAULT CURRENT_TIMESTAMP,
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `accounts_id` PRIMARY KEY(`id`)
);
